"use client";

import { useState, useRef } from "react";
import { motion, AnimatePresence, useInView } from "framer-motion";
import { X, Check, Clock, Puzzle, Target, MessageSquare, Cpu, Download, Presentation, ClipboardList, BookOpen, BarChart3, GraduationCap, Image, Brain, Globe, Users, Lightbulb } from "lucide-react";
import { TiltCard } from "@/components/motion/TiltCard";

const ease: [number, number, number, number] = [0.25, 0.1, 0.25, 1];

type TabKey = "why" | "how" | "what";

const tabs: { key: TabKey; label: string }[] = [
  { key: "why", label: "Why InquiryGen" },
  { key: "how", label: "How It Works" },
  { key: "what", label: "What You Get" },
];

/* ─── Why Tab Data ─── */
const oldWay = [
  "Hours searching Teachers Pay Teachers",
  "Copy-pasting from multiple sources",
  "Misaligned standards and assessments",
  "Generic worksheets without inquiry",
  "Starting from scratch every unit",
];

const newWay = [
  "Complete units in minutes",
  "Coherent, research-backed sequences",
  "Automatically aligned to standards",
  "Authentic inquiry with student agency",
  "Customizable templates that grow",
];

const obstacles = [
  { icon: Clock, stat: "8-15 hrs", statLabel: "per unit", title: "Time-Starved Teachers" },
  { icon: Puzzle, stat: "3+", statLabel: "sources needed", title: "Fragmented Resources" },
  { icon: Target, stat: "0%", statLabel: "perfect match", title: "Standards Misalignment" },
];

/* ─── How Tab Data ─── */
const steps = [
  { number: "01", icon: MessageSquare, title: "Describe Your Lesson", description: "Enter your topic, grade level, and standards framework. Choose an inquiry model or let InquiryGen recommend one." },
  { number: "02", icon: Cpu, title: "AI Builds Your Unit", description: "Our AI generates a complete unit: teacher guide, student presentation, activity pack, rubrics, and assessments." },
  { number: "03", icon: Download, title: "Review, Edit & Export", description: "Preview everything in-browser. Edit any section. Regenerate what you don\u2019t like. Export to PowerPoint and Word." },
];

/* ─── What Tab Data ─── */
const deliverables = [
  { icon: Presentation, title: "Student Presentation", format: ".pptx", description: "Branded slides with engaging visuals, discussion prompts, vocabulary, and structured inquiry activities." },
  { icon: ClipboardList, title: "Student Activity Pack", format: ".docx", description: "Pre-assessment, rubric, component analysis, model sketching, simulation observations, and reflection." },
  { icon: BookOpen, title: "Teacher\u2019s Guide", format: ".docx", description: "Standards unpacking, background content, slide-by-slide facilitation, answer key, and differentiation." },
  { icon: BarChart3, title: "Standards Alignment", format: null, description: "Automatically mapped to your national curriculum — IB, UK, Australian, NGSS, and 50+ country-specific frameworks." },
  { icon: GraduationCap, title: "Assessment Suite", format: null, description: "Pre-assessment, formative checks, rubrics, and summative reflection aligned to learning objectives." },
  { icon: Image, title: "AI-Generated Visuals", format: null, description: "Contextual images for student slides generated by AI \u2014 no more searching for stock photos." },
];

/* ─── Pedagogy Icons ─── */
const principles = [
  { icon: Brain, label: "Inquiry-Based Learning" },
  { icon: Globe, label: "Global Standards" },
  { icon: Users, label: "CAST Framework" },
  { icon: Lightbulb, label: "UDL Principles" },
];

/* ─── Tab Content Components ─── */

function WhyTab() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-50px" });

  return (
    <div ref={ref} className="grid gap-8 lg:grid-cols-[1fr_auto_1fr]">
      {/* Old Way vs New Way */}
      <div className="space-y-6">
        <div className="liquid-glass-subtle p-6">
          <h4 className="font-display text-lg text-red-600">The Old Way</h4>
          <ul className="mt-4 space-y-3">
            {oldWay.map((item, i) => (
              <motion.li
                key={item}
                initial={{ opacity: 0, x: -10 }}
                animate={isInView ? { opacity: 1, x: 0 } : {}}
                transition={{ duration: 0.4, delay: 0.08 * i, ease }}
                className="flex items-start gap-2.5 text-sm text-red-700/70"
              >
                <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-red-500/10">
                  <X className="h-3 w-3 text-red-500" />
                </span>
                {item}
              </motion.li>
            ))}
          </ul>
        </div>
        <div className="liquid-glass-subtle p-6">
          <h4 className="font-display text-lg text-emerald-600">The InquiryGen Way</h4>
          <ul className="mt-4 space-y-3">
            {newWay.map((item, i) => (
              <motion.li
                key={item}
                initial={{ opacity: 0, x: -10 }}
                animate={isInView ? { opacity: 1, x: 0 } : {}}
                transition={{ duration: 0.4, delay: 0.08 * i + 0.3, ease }}
                className="flex items-start gap-2.5 text-sm text-emerald-700/70"
              >
                <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-emerald-500/10">
                  <Check className="h-3 w-3 text-emerald-500" />
                </span>
                {item}
              </motion.li>
            ))}
          </ul>
        </div>
      </div>

      {/* Center divider */}
      <div className="hidden items-center justify-center lg:flex">
        <motion.div
          className="h-3/4 w-px bg-gradient-to-b from-transparent via-[#10b981]/30 to-transparent"
          initial={{ scaleY: 0 }}
          animate={isInView ? { scaleY: 1 } : {}}
          transition={{ duration: 0.8, delay: 0.3, ease }}
        />
      </div>

      {/* Stat Cards */}
      <div className="flex flex-col gap-4">
        {obstacles.map((item, i) => (
          <motion.div
            key={item.title}
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5, delay: 0.15 * (i + 1), ease }}
          >
            <TiltCard className="liquid-glass-subtle p-5 text-center" maxTilt={6}>
              <div className="mx-auto inline-flex rounded-xl bg-[#10b981]/10 p-3">
                <item.icon className="h-6 w-6 text-[#10b981]" />
              </div>
              <h4 className="font-display mt-3 text-sm text-[#475569]">{item.title}</h4>
              <div className="mt-1">
                <span className="font-display bg-gradient-to-r from-[#10b981] to-[#34d399] bg-clip-text text-2xl font-bold text-transparent">
                  {item.stat}
                </span>
                <span className="ml-1 text-xs text-[#475569]/60">{item.statLabel}</span>
              </div>
            </TiltCard>
          </motion.div>
        ))}
      </div>
    </div>
  );
}

function HowTab() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-50px" });

  return (
    <div ref={ref}>
      <div className="relative grid gap-8 md:grid-cols-3">
        {/* Connecting line (desktop) */}
        <div className="absolute top-9 left-[16.6%] right-[16.6%] hidden md:block">
          <div className="h-[2px] w-full bg-[#0f172a]/5">
            <motion.div
              className="h-full bg-gradient-to-r from-[#10b981]/30 via-[#10b981]/60 to-[#10b981]/30"
              initial={{ width: "0%" }}
              animate={isInView ? { width: "100%" } : {}}
              transition={{ duration: 1.5, delay: 0.5, ease }}
            />
          </div>
        </div>

        {steps.map((step, i) => (
          <motion.div
            key={step.number}
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.2 * (i + 1), ease }}
            className="relative text-center"
          >
            <motion.div
              className="mx-auto flex h-[72px] w-[72px] items-center justify-center rounded-2xl liquid-glass-subtle"
              animate={
                isInView
                  ? { boxShadow: "0 0 35px rgba(16,185,129,0.15)" }
                  : {}
              }
              transition={{ duration: 0.8, delay: 0.4 * (i + 1) }}
            >
              <step.icon className="h-8 w-8 text-[#10b981]" />
            </motion.div>
            <motion.div
              className="mt-3 inline-flex rounded-full bg-[#10b981]/10 px-3 py-1 text-xs font-bold uppercase tracking-widest text-[#10b981]"
              animate={isInView ? { animation: "pulseGlow 2s ease-in-out infinite" } : {}}
            >
              Step {step.number}
            </motion.div>
            <h4 className="font-display mt-3 text-lg text-[#0f172a]">{step.title}</h4>
            <p className="mt-2 text-sm leading-relaxed text-[#475569]">{step.description}</p>
          </motion.div>
        ))}
      </div>
    </div>
  );
}

function WhatTab() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-50px" });

  return (
    <div ref={ref} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      {deliverables.map((item, i) => (
        <motion.div
          key={item.title}
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5, delay: 0.1 * (i + 1), ease }}
          whileHover={{ y: -4 }}
          className="liquid-glass-subtle glass-shimmer group p-5"
        >
          <div className="inline-flex rounded-xl bg-[#10b981]/10 p-3 transition-shadow duration-300 group-hover:shadow-[0_0_20px_rgba(16,185,129,0.15)]">
            <item.icon className="h-5 w-5 text-[#10b981]" />
          </div>
          <h4 className="mt-3 text-sm font-semibold text-[#0f172a]">
            {item.title}
            {item.format && (
              <span className="badge-shimmer ml-2 inline-block rounded-md border border-[#10b981]/20 bg-[#10b981]/10 px-2 py-0.5 text-xs font-medium text-[#10b981]">
                {item.format}
              </span>
            )}
          </h4>
          <p className="mt-2 text-xs leading-relaxed text-[#475569]">{item.description}</p>
        </motion.div>
      ))}
    </div>
  );
}

const tabContent: Record<TabKey, React.ReactNode> = {
  why: <WhyTab />,
  how: <HowTab />,
  what: <WhatTab />,
};

/* ─── Main Component ─── */
export function TabbedShowcase() {
  const [activeTab, setActiveTab] = useState<TabKey>("why");

  return (
    <section id="features" className="relative min-h-screen py-24">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        {/* Tab bar */}
        <div className="mx-auto mb-12 flex w-fit gap-1 rounded-full border border-[#0f172a]/10 bg-[#0f172a]/[0.03] p-1.5">
          {tabs.map((tab) => (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key)}
              className={`relative rounded-full px-6 py-2.5 text-sm font-medium transition-colors ${
                activeTab === tab.key ? "text-[#0f172a]" : "text-[#475569] hover:text-[#0f172a]/70"
              }`}
            >
              {activeTab === tab.key && (
                <motion.div
                  layoutId="tab-pill"
                  className="liquid-glass-tab absolute inset-0"
                  transition={{ type: "spring", stiffness: 400, damping: 30 }}
                />
              )}
              <span className="relative z-10">{tab.label}</span>
            </button>
          ))}
        </div>

        {/* Tab content */}
        <div className="liquid-glass glass-refraction glass-glow p-8 sm:p-10">
          <AnimatePresence mode="wait">
            <motion.div
              key={activeTab}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -12 }}
              transition={{ duration: 0.3, ease }}
            >
              {tabContent[activeTab]}
            </motion.div>
          </AnimatePresence>
        </div>

        {/* Pedagogy icon bar */}
        <div className="mt-8 flex flex-wrap items-center justify-center gap-6">
          {principles.map((p, i) => (
            <motion.div
              key={p.label}
              initial={{ opacity: 0, y: 10 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: 0.1 * i }}
              className="liquid-glass-subtle flex items-center gap-3 px-5 py-3"
            >
              <motion.div
                whileHover={{ rotate: 360, scale: 1.1 }}
                transition={{ duration: 0.6, ease: "easeInOut" }}
                className="rounded-lg bg-[#10b981]/10 p-2"
              >
                <p.icon className="h-4 w-4 text-[#10b981]" />
              </motion.div>
              <span className="text-xs font-medium text-[#475569]">{p.label}</span>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
