"use client";

import { useRef } from "react";
import { motion, useInView } from "framer-motion";
import {
  Presentation,
  ClipboardList,
  BookOpen,
  BarChart3,
  GraduationCap,
  Image,
} from "lucide-react";
import { TextReveal } from "@/components/motion/TextReveal";

const ease: [number, number, number, number] = [0.25, 0.1, 0.25, 1];

const deliverables = [
  {
    icon: Presentation,
    title: "Student Presentation",
    format: ".pptx",
    description:
      "Branded slides with engaging visuals, discussion prompts, vocabulary, and structured inquiry activities.",
  },
  {
    icon: ClipboardList,
    title: "Student Activity Pack",
    format: ".docx",
    description:
      "Pre-assessment, rubric, component analysis, model sketching, simulation observations, and reflection.",
  },
  {
    icon: BookOpen,
    title: "Teacher\u2019s Guide",
    format: ".docx",
    description:
      "Standards unpacking, background content, slide-by-slide facilitation, answer key, and differentiation strategies.",
  },
  {
    icon: BarChart3,
    title: "Standards Alignment",
    format: null,
    description:
      "Automatically mapped to NGSS, state standards, IB, UK National Curriculum, or Australian Curriculum.",
  },
  {
    icon: GraduationCap,
    title: "Assessment Suite",
    format: null,
    description:
      "Pre-assessment, formative checks, rubrics, and summative reflection \u2014 all aligned to your learning objectives.",
  },
  {
    icon: Image,
    title: "AI-Generated Visuals",
    format: null,
    description:
      "Contextual images for student slides generated by AI \u2014 no more searching for stock photos.",
  },
];

export function WhatYouGet() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });

  return (
    <section ref={ref} className="dot-grid-light relative bg-[#f8fafc] py-24">
      <div className="relative z-10 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          <TextReveal
            as="h2"
            className="font-display text-3xl tracking-tight text-foreground sm:text-4xl"
          >
            What You Get
          </TextReveal>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.3, ease }}
            className="mt-4 text-lg text-muted-foreground"
          >
            Every generation produces a complete, ready-to-teach unit package.
          </motion.p>
        </div>

        <div className="mt-16 bento-grid">
          {deliverables.map((item, i) => {
            const isWide = i === 0 || i === 3;
            return (
              <motion.div
                key={item.title}
                initial={{ opacity: 0, y: 20 }}
                animate={isInView ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.5, delay: 0.12 * (i + 1), ease }}
                whileHover={{ y: -6 }}
                className={`accent-bar card-hover group rounded-2xl border border-border bg-white p-6 shadow-sm ${
                  isWide ? "bento-span-2" : ""
                }`}
              >
                <div className={isWide ? "flex items-start gap-6" : ""}>
                  <div className="inline-flex rounded-xl bg-gradient-to-br from-[#10b981]/15 to-[#10b981]/5 p-3 transition-shadow duration-300 group-hover:shadow-[0_0_20px_rgba(16,185,129,0.15)]">
                    <item.icon className="h-5 w-5 text-[#10b981]" />
                  </div>
                  <div className={isWide ? "flex-1" : ""}>
                    <h3 className={`${isWide ? "" : "mt-4"} text-base font-semibold`}>
                      {item.title}
                      {item.format && (
                        <span className="badge-shimmer ml-2 inline-block rounded-md border border-[#10b981]/20 bg-[#10b981]/5 px-2 py-0.5 text-xs font-medium text-[#10b981]">
                          {item.format}
                        </span>
                      )}
                    </h3>
                    <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                      {item.description}
                    </p>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
