import PptxGenJS from "pptxgenjs";

type SlideContent = {
  slideNumber: number;
  title: string;
  layout: string;
  content: {
    mainText?: string;
    bulletPoints?: string[];
    activityInstructions?: string;
    discussionPrompt?: string;
    imageDescription?: string;
  };
  speakerNotes: string;
  inquiryPhase: string;
};

type PresentationContent = {
  slides: SlideContent[];
};

type BrandingConfig = {
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  fontFamily: string;
};

const DEFAULT_BRANDING: BrandingConfig = {
  primaryColor: "2563EB",
  secondaryColor: "1E40AF",
  accentColor: "F59E0B",
  fontFamily: "Arial",
};

export async function buildPresentation(
  content: PresentationContent,
  unitTitle: string,
  gradeLevel: string,
  branding: BrandingConfig = DEFAULT_BRANDING
): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "InquiryGen";
  pptx.title = unitTitle;

  for (const slide of content.slides) {
    const pptxSlide = pptx.addSlide();

    // Add speaker notes
    pptxSlide.addNotes(slide.speakerNotes);

    switch (slide.layout) {
      case "title":
        buildTitleSlide(pptxSlide, slide, gradeLevel, branding);
        break;
      case "content":
        buildContentSlide(pptxSlide, slide, branding);
        break;
      case "two_column":
        buildTwoColumnSlide(pptxSlide, slide, branding);
        break;
      case "activity":
        buildActivitySlide(pptxSlide, slide, branding);
        break;
      case "reflection":
        buildReflectionSlide(pptxSlide, slide, branding);
        break;
      case "image_focus":
        buildImageFocusSlide(pptxSlide, slide, branding);
        break;
      default:
        buildContentSlide(pptxSlide, slide, branding);
    }

    // Slide number
    pptxSlide.addText(
      `${slide.slideNumber} / ${content.slides.length}`,
      {
        x: 11.5,
        y: 7,
        w: 1.5,
        h: 0.3,
        fontSize: 9,
        color: "999999",
        align: "right",
      }
    );
  }

  const arrayBuffer = await pptx.write({ outputType: "arraybuffer" });
  return Buffer.from(arrayBuffer as ArrayBuffer);
}

function buildTitleSlide(
  slide: PptxGenJS.Slide,
  content: SlideContent,
  gradeLevel: string,
  branding: BrandingConfig
) {
  // Background accent bar
  slide.addShape("rect" as any, {
    x: 0,
    y: 0,
    w: 13.33,
    h: 3,
    fill: { color: branding.primaryColor },
  });

  // Title
  slide.addText(content.title, {
    x: 0.5,
    y: 0.8,
    w: 12,
    h: 1.5,
    fontSize: 36,
    bold: true,
    color: "FFFFFF",
    fontFace: branding.fontFamily,
  });

  // Subtitle / main text
  if (content.content.mainText) {
    slide.addText(content.content.mainText, {
      x: 0.5,
      y: 3.5,
      w: 12,
      h: 2,
      fontSize: 18,
      color: "333333",
      fontFace: branding.fontFamily,
    });
  }

  // Grade level badge
  slide.addText(`Grade ${gradeLevel}`, {
    x: 0.5,
    y: 6.5,
    w: 2,
    h: 0.5,
    fontSize: 12,
    bold: true,
    color: branding.primaryColor,
    fontFace: branding.fontFamily,
  });

  // InquiryGen branding
  slide.addText("Generated by InquiryGen", {
    x: 9,
    y: 6.5,
    w: 4,
    h: 0.5,
    fontSize: 10,
    color: "999999",
    align: "right",
    fontFace: branding.fontFamily,
  });
}

function buildContentSlide(
  slide: PptxGenJS.Slide,
  content: SlideContent,
  branding: BrandingConfig
) {
  // Header bar
  slide.addShape("rect" as any, {
    x: 0,
    y: 0,
    w: 13.33,
    h: 1.2,
    fill: { color: branding.primaryColor },
  });

  // Title
  slide.addText(content.title, {
    x: 0.5,
    y: 0.15,
    w: 12,
    h: 0.9,
    fontSize: 24,
    bold: true,
    color: "FFFFFF",
    fontFace: branding.fontFamily,
  });

  // Phase badge
  slide.addText(content.inquiryPhase, {
    x: 10.5,
    y: 0.15,
    w: 2.5,
    h: 0.4,
    fontSize: 10,
    color: "FFFFFF",
    align: "right",
    fontFace: branding.fontFamily,
  });

  let yPos = 1.5;

  // Main text
  if (content.content.mainText) {
    slide.addText(content.content.mainText, {
      x: 0.5,
      y: yPos,
      w: 12,
      h: 1.5,
      fontSize: 16,
      color: "333333",
      fontFace: branding.fontFamily,
    });
    yPos += 1.8;
  }

  // Bullet points
  if (content.content.bulletPoints?.length) {
    const bullets = content.content.bulletPoints.map((bp) => ({
      text: bp,
      options: { bullet: { type: "bullet" as const }, fontSize: 14 },
    }));
    slide.addText(bullets, {
      x: 0.8,
      y: yPos,
      w: 11,
      h: 4,
      color: "333333",
      fontFace: branding.fontFamily,
      paraSpaceAfter: 8,
    });
  }

  // Discussion prompt
  if (content.content.discussionPrompt) {
    slide.addShape("rect" as any, {
      x: 0.5,
      y: 6,
      w: 12,
      h: 0.8,
      fill: { color: "FFF8E1" },
      rectRadius: 0.1,
    });
    slide.addText(`Think About It: ${content.content.discussionPrompt}`, {
      x: 0.7,
      y: 6.1,
      w: 11.6,
      h: 0.6,
      fontSize: 13,
      italic: true,
      color: branding.accentColor,
      fontFace: branding.fontFamily,
    });
  }
}

function buildTwoColumnSlide(
  slide: PptxGenJS.Slide,
  content: SlideContent,
  branding: BrandingConfig
) {
  // Same header as content slide
  slide.addShape("rect" as any, {
    x: 0,
    y: 0,
    w: 13.33,
    h: 1.2,
    fill: { color: branding.primaryColor },
  });

  slide.addText(content.title, {
    x: 0.5,
    y: 0.15,
    w: 12,
    h: 0.9,
    fontSize: 24,
    bold: true,
    color: "FFFFFF",
    fontFace: branding.fontFamily,
  });

  // Left column
  if (content.content.mainText) {
    slide.addText(content.content.mainText, {
      x: 0.5,
      y: 1.5,
      w: 5.8,
      h: 5,
      fontSize: 14,
      color: "333333",
      fontFace: branding.fontFamily,
    });
  }

  // Right column - bullet points
  if (content.content.bulletPoints?.length) {
    const bullets = content.content.bulletPoints.map((bp) => ({
      text: bp,
      options: { bullet: { type: "bullet" as const }, fontSize: 13 },
    }));
    slide.addText(bullets, {
      x: 7,
      y: 1.5,
      w: 5.8,
      h: 5,
      color: "333333",
      fontFace: branding.fontFamily,
    });
  }
}

function buildActivitySlide(
  slide: PptxGenJS.Slide,
  content: SlideContent,
  branding: BrandingConfig
) {
  // Green accent header for activities
  slide.addShape("rect" as any, {
    x: 0,
    y: 0,
    w: 13.33,
    h: 1.2,
    fill: { color: "16A34A" },
  });

  slide.addText(`Activity: ${content.title}`, {
    x: 0.5,
    y: 0.15,
    w: 12,
    h: 0.9,
    fontSize: 24,
    bold: true,
    color: "FFFFFF",
    fontFace: branding.fontFamily,
  });

  // Activity instructions
  if (content.content.activityInstructions) {
    slide.addText(content.content.activityInstructions, {
      x: 0.5,
      y: 1.5,
      w: 12,
      h: 4.5,
      fontSize: 15,
      color: "333333",
      fontFace: branding.fontFamily,
      paraSpaceAfter: 6,
    });
  }
}

function buildReflectionSlide(
  slide: PptxGenJS.Slide,
  content: SlideContent,
  branding: BrandingConfig
) {
  // Purple accent for reflection
  slide.addShape("rect" as any, {
    x: 0,
    y: 0,
    w: 13.33,
    h: 1.2,
    fill: { color: "7C3AED" },
  });

  slide.addText(content.title, {
    x: 0.5,
    y: 0.15,
    w: 12,
    h: 0.9,
    fontSize: 24,
    bold: true,
    color: "FFFFFF",
    fontFace: branding.fontFamily,
  });

  if (content.content.mainText) {
    slide.addText(content.content.mainText, {
      x: 0.5,
      y: 1.5,
      w: 12,
      h: 2,
      fontSize: 16,
      color: "333333",
      fontFace: branding.fontFamily,
    });
  }

  if (content.content.discussionPrompt) {
    slide.addShape("rect" as any, {
      x: 1,
      y: 3.5,
      w: 11,
      h: 2.5,
      fill: { color: "F3E8FF" },
      rectRadius: 0.15,
    });
    slide.addText(content.content.discussionPrompt, {
      x: 1.3,
      y: 3.7,
      w: 10.4,
      h: 2.1,
      fontSize: 18,
      italic: true,
      color: "5B21B6",
      align: "center",
      fontFace: branding.fontFamily,
    });
  }
}

function buildImageFocusSlide(
  slide: PptxGenJS.Slide,
  content: SlideContent,
  branding: BrandingConfig
) {
  // Same as content but with placeholder for image
  buildContentSlide(slide, content, branding);

  // Add image placeholder text
  if (content.content.imageDescription) {
    slide.addShape("rect" as any, {
      x: 8,
      y: 1.5,
      w: 4.8,
      h: 4.5,
      fill: { color: "F1F5F9" },
      rectRadius: 0.1,
      line: { color: "CBD5E1", width: 1 },
    });
    slide.addText("[AI Image: " + content.content.imageDescription + "]", {
      x: 8.2,
      y: 2.5,
      w: 4.4,
      h: 2.5,
      fontSize: 10,
      color: "94A3B8",
      align: "center",
      fontFace: branding.fontFamily,
    });
  }
}
